#2024-04-04 <mm> created
blueprint:
  name: MQTT - SBBT-002C
  description: ShellbyBLU Button1
  domain: automation
  input:
    shellyblu_button:
      name: ShellyBlu Button1
      description: ShellyBLU Button1 SBBT-002C-press
      selector:
        entity:
          domain: sensor

    button_single:
      name: Button | Single Press
      description: Action to run on single press
      default: []
      selector:
        action: {}
    button_double:
      name: Button | Double Press
      description: Action to run on double press
      default: []
      selector:
        action: {}
    button_triple:
      name: Button | Triple Press
      description: Action to run on triple press
      default: []
      selector:
        action: {}
    button_hold:
      name: Button | Hold Press
      description: Action to run on hold press
      default: []
      selector:
        action: {}

mode: single
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input shellyblu_button

###### https://decoder.theengs.io/devices/SBBT-002C.html
### Event
# single
# double
# triple
# hold                        // > 3 sec hold

action:
  - choose:
      - conditions:
        entity_id: !input shellyblu_button
        state: "1"
        sequence: !input "button_single"
      - conditions:
        entity_id: !input shellyblu_button
        state: "2"
        sequence: !input "button_double"
      - conditions:
        entity_id: !input shellyblu_button
        state: "3"
        sequence: !input "button_triple" 
      - conditions:
        entity_id: !input shellyblu_button
        state: "4"
        sequence: !input "button_hold"
